name: test-if
on: 
 push:
    branches:
      - main
      - test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: run if test branch push
        if: github.ref_name =='test'
        run: echo "this is test"
      - name: run this step
        run: echo "this is manual"
     
 
