name: test
on: workflow_dispatch
jobs:
  job:
    runs-on: ubuntu-latest
    steps: 
      - run: echo " hello"   
      - run: date 
      - run: uname -a
      - run: free -h
      - run: du -hT      
  
